SELECT  * FROM TB_PRODUTOS;

-- USADO PARA INSERIR E DUPLICAR COMO EXEMPLO
INSERT INTO TB_PRODUTOS 
(PRODUTO,NOME,EMBALAGEM,TAMANHO,SABOR,PRECO_LISTA)
VALUES
('1037797','Clean - 2 Litros - Laranja','PET','2 Litros ','Laranja',16.01);


--DELETAR AS LINHAS QUE ESTAM DUPLICADAS
DELETE FROM TB_PRODUTOS WHERE PRODUTO = '1037797'

-- ADICIONANDO CHAVE PRIMÁRIA
ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS  PRIMARY KEY (PRODUTO);



