SELECT * FROM TB_VENDEDORES;

INSERT INTO TB_VENDEDORES 
(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES
('00233','Joao Geraldo da Fonseca',TO_DATE('01/12/2015', 'DD/MM/YYYY'),0.10);


ALTER TABLE TB_VENDEDORES ADD CONSTRAINT PK_TB_VENDEDORES PRIMARY KEY(MATRICULA);