SELECT * FROM TB_VENDEDORES;


-- Inserts exercicio
INSERT INTO TB_VENDEDORES 
(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES
('00265','Jonh Wayne',TO_DATE('27/03/2019', 'DD/MM/YYYY'),0.12);

INSERT INTO TB_VENDEDORES 
(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES
('00777','Katy Peterson',TO_DATE('04/02/2020', 'DD/MM/YYYY'),0.10);

INSERT INTO TB_VENDEDORES 
(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES
('00342','Rodrigo Almeida',TO_DATE('18/01/2022', 'DD/MM/YYYY'),0.09);

INSERT INTO TB_VENDEDORES 
(MATRICULA,NOME,DATA_ADMISSAO,PERCENTUAL_COMISSAO)
VALUES
('00729','Patricia Martins',TO_DATE('02/01/2022', 'DD/MM/YYYY'),0.09);

